### ISSUE TITLE
RXPConvert BUG

### ISSUE THREAD

**Issue by KateBrodie** [FRF-Remote-Sensing/Utilities#11]
@atdyer @hokiespurs 

So @njspore and I are at our wits end.....RXPconvert.exe on a windows machine cannot successfully convert an rxp file collected on reggie (i dont know if this is the new collect code or a linux environment being the problem).  It works fine on the old rxp files created up to September 10.  It also works fine on a linux machine (obviously).  It also works fine in one case I detail below.  RXPconvert thinks it's converting the file, outputs to the screen that it's done it and tells me its written 8 million points and the name and location of the *.bin file, but the *.bin file is never actually created...or gets LOST!? I'm completely perplexed. 

 - from the command prompt inside the directory where the files are, I ran: P:\Realtime_dune_lidar\Raw\20150920-2200-01.FRFNProp>RXPconvert.exe P:\Realtime_
dune_lidar\Raw\20150910-2200-01.FRFNProp\20150910-2241-17.FRFNProp.frame.rxp P:\
Realtime_dune_lidar\Raw\20150910-2200-01.FRFNProp/20150910-2241-17.FRFNProp.fram
e.bin allpoints x y z r tgps  I then did dir *.bin and there were no files found.

 - from matlab, i ran readLidar within the directory: [data, varargout] = readLidar('20150910-2241-17.FRFNProp.frame.rxp'); the tmpfile name is simply  '/20150910-2241-17.FRFNProp.frame.bin' and if you run an exist command, matlab finds it, but a dir() command shows no .bin files in the directory!?! however readLidar will find the file and finish what it's supposed to do. 

- from matlab i run readLidar with the whole directory path: [data, varargout] = readLidar('P:\Realtime_dune_lidar\Raw\20150910-2200-01.FRFNProp\20150910-2241-17.FRFNProp.frame.rxp'); the tmpfile name is now 'P:\Realtime_dune_lidar\Raw\20150910-2200-01.FRFNProp/20150910-2241-17.FRFNProp.frame.bin', but when you run exist you get '0', and dir also returns no .bin files in that directory. 

- if i run any of these cases on a file that was collected pre sep 10 (when we switched to reggie), they all work fine. I can also do any of these  on linux (once I remember to give it the path to rxpconvert.exe). 

HELP!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by atdyer** [comment]
@KateBrodie 

Absolutely no idea what's going on here. Did running github as administrator help that permissions issue earlier? Maybe it's also a permissions issue? What machine are you running it on? And have you tried a different Windows machine and got the same results?

**Comment by hokiespurs** [comment]
@KateBrodie @atdyer @njspore 

> if you run an exist command, matlab finds it, but a dir() command shows no .bin files in the directory


This sounds like it's writing the file to a system path and not the absolute path that you want it to. 

That would explain why exist(filename) finds it but exist(fullpath) doesnt.

For example.  exist('cameraman.tif') works... because its in the system path.  See if you can search the computer to find the file, I'd start by looking in the same directory as the exe.

**Comment by hokiespurs** [comment]
@KateBrodie @atdyer @njspore 

So to summarize the symptoms.

---

ONLY for new files, the exe does not save the *.bin to the correct location.  It may save it to another location on the system.  If you run this command for old files, dir *.bin shows files?

``` dos 
P:\Realtime_dune_lidar\Raw\20150920-2200-01.FRFNProp>RXPconvert.exe 
   P:\Realtime_dune_lidar\Raw\20150910-2200-01.FRFNProp\20150910-2241-17.FRFNProp.frame.rxp 
   P:\Realtime_dune_lidar\Raw\20150910-2200-01.FRFNProp/20150910-2241-17.FRFNProp.frame.bin
   allpoints x y z r tgps 

dir *.bin
```

Can you change the filenames of some of the older files to confirm that it is a linux issue, and not a naming convention?  Maybe rename a file from August to follow the same convention as late September, and see what happens.

It doesn't make sense how the content of the RXP file would affect the exe's ability to write out a valid binary file to the correct location

--- 

For the example when Matlab finds the file with exist but not dir, can you use this code:

```matlab
filename = '20150910-2241-17.FRFNProp.frame.bin';
exist(filename)
dir('*.bin')
filelocation = which(filename)
```

"which()" gives you the absolute location of the file, and should tell us how exist is finding it, but dir is not.

**Comment by KateBrodie** [comment]
- we've tried it on both my machine and nick's machine with the same results
 - which(tmpfile)
'/20150910-2241-17.FRFNProp.frame.bin' not found.
 - exist(tmpfile)
ans =2
- dir('*.bin')
'*.bin' not found.

**Comment by hokiespurs** [comment]
@katebrodie

Can you try exist(tmpname,'file')

Can you also try to search the cpu for the file to see if it exists
somewhere else.

**Comment by KateBrodie** [comment]
@hokiespurs i updated my last post. 

 - I found them. in the top level of P drive (Peeler).
 - exist(tmpfile,'file') also returns 2
 - if i run it on old files in the command prompt dir *.bin does not find any files, but in matlab dir() does find the *.bin

**Comment by hokiespurs** [comment]
@katebrodie @atdyer

What if you write the temp files to a local drive and not the shared drive?
Could it have something to do with Linux and how it sets permissions on the
file?

**Comment by KateBrodie** [comment]
@hokiespurs @atdyer 

Ok, so I ran it from the command prompt on a new file and told it to put the temp file on my local D drive and it worked. I also ran it from readLidar and forced tmpfile to be on my D drive:

.. matlab
    [filepath, filename, ~] = fileparts(files{i});
    %tmpfile = [filepath '/' filename '.bin'];
    tmpfile = ['D:/' filename '.bin'];

and that worked. it made .bin on my D Drive. but this is totally bizarre, that the old files work without me having to do that. maybe it's the write permissions in each hour's directory that aren't being made correctly with the new linux based collect??? Since nick and I arent administrators on the windows RDE machines?  where as the old directories were created with windows protocol? i'm really grasping at straws here.

**Comment by KateBrodie** [comment]
@hokiespurs @atdyer 

YEP. I dont have write permission in folders created on peeler with the new collect code.

**Comment by atdyer** [comment]
@KateBrodie @hokiespurs 

Not exactly sure why the permissions are being set that way, I'll take a look at it when I'm there tomorrow. Here's what to do. Do this from Reggie:

```bash
$> cd /path/to/peeler/
$> ls -lah
```

This should give a list of all files and directories at the top level of Peeler, along with all of their permissions. The left-most column for each file/folder will look something like this:

**-rw-rw-r--**

If you cd into Realtime_dune_lidar/Raw and do another ls -lah (which might take a minute because there are tons of files in there) you should see the same thing. The last three characters of that line (r--) are the permissions that all users have for that file/folder. The three characters before that (rw-) are the user group permissions, and the three before that (rw-) are the owner's permissions. The **r--** means read only permission. The **rw-** means read and write permissions, and an **rwx** would mean read, write, and execute permissions.

So to fix the issue, we need to either add the computers you're using to the user group (assuming the group also has read/write permission), or set the the permissions of all files and folders to allow all users to read/write.

To change all **directories** to have read and write permissions for all users, run the following command from the top level of Peeler:
```bash
find Realtime_dune_lidar/ -type d -exec chmod a+rw {} \;
```
This will let you make new files in any of the directories on Peeler from any computer.

To change all **files** to have read and write permissions for all users, run the following command from the top level of Peeler:
```bash
find Realtime_dune_lidar/ -type f -exec chmod a+rw {} \;
```
This will let you read and write to files that were created by Reggie using a different computer. You shouldn't need this because it seems like you already have read permissions and you shouldn't need to edit the rxp files so you don't need write permissions.

### Sparknotes
To change the permissions of a single directory to include read and write permissions for all users:
```bash
chmod a+rw /path/to/directory
```

**Comment by atdyer** [comment]
Fixed!
